/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotdc;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    ArrayList<Nodo> listaNodos = new ArrayList();
    ArrayList<Linea> lines = new ArrayList();
    Graphics g;
    Graphics c;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        g = this.jp_pizarra.getGraphics();
        c = this.jp_pizarra.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_mainpanel = new javax.swing.JPanel();
        jb_agregarnodo = new javax.swing.JButton();
        jb_limpiar = new javax.swing.JButton();
        jp_pizarra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_camino = new javax.swing.JTextField();
        jb_dibujar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtf_origen = new javax.swing.JTextField();
        jtf_destino = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_mainpanel.setBackground(new java.awt.Color(0, 0, 0));

        jb_agregarnodo.setText("Nuevo Nodo");
        jb_agregarnodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarnodoActionPerformed(evt);
            }
        });

        jb_limpiar.setText("Limpiar");
        jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_pizarraLayout = new javax.swing.GroupLayout(jp_pizarra);
        jp_pizarra.setLayout(jp_pizarraLayout);
        jp_pizarraLayout.setHorizontalGroup(
            jp_pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        jp_pizarraLayout.setVerticalGroup(
            jp_pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Ingrese un camino valido(ejem: 1,2,3,4)");

        jtf_camino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_caminoActionPerformed(evt);
            }
        });

        jb_dibujar.setText("Dibujar");
        jb_dibujar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_dibujarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("GRAPHICS E&D");

        jtf_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_destinoActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Origen");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destino");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("DRAW LINE");

        jButton1.setText("-->");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_mainpanelLayout = new javax.swing.GroupLayout(jp_mainpanel);
        jp_mainpanel.setLayout(jp_mainpanelLayout);
        jp_mainpanelLayout.setHorizontalGroup(
            jp_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mainpanelLayout.createSequentialGroup()
                .addGroup(jp_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_mainpanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jb_dibujar))
                    .addGroup(jp_mainpanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jp_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jp_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jtf_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addGroup(jp_mainpanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jp_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_agregarnodo)
                            .addComponent(jb_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jp_pizarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_camino, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(96, 96, 96))
        );
        jp_mainpanelLayout.setVerticalGroup(
            jp_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mainpanelLayout.createSequentialGroup()
                .addGroup(jp_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_mainpanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_mainpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_camino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jp_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_mainpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(jb_agregarnodo)
                        .addGap(67, 67, 67)
                        .addComponent(jb_limpiar)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jp_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jb_dibujar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_mainpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jp_pizarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_caminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_caminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_caminoActionPerformed

    private void jb_agregarnodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarnodoActionPerformed
        cont++;
        Nodo nodo = new Nodo(cont);
        jp_pizarra.add(nodo);
        listaNodos.add(nodo);
        nodo.updateUI();
//        for (int i = 0; i < lines.size() ; i++) {
//            for (int j = 0; j < lines.size(); j++) {
//                g.drawLine(listaNodos.get(lines.get(i).getX()).getX(), listaNodos.get(lines.get(i).getY()).getY(), listaNodos.get(lines.get(j).getX()).getX(), listaNodos.get(lines.get(j).getX()).getX());
//            }
//        }
    }//GEN-LAST:event_jb_agregarnodoActionPerformed

    private void jtf_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_destinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_destinoActionPerformed

    private void jb_dibujarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_dibujarMouseClicked
        if (jtf_origen.getText().equals("") || jtf_destino.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Tiene argumentos vacios");
        } else {
            g.drawLine(listaNodos.get(Integer.parseInt(jtf_origen.getText()) - 1).getX() + 5, listaNodos.get(Integer.parseInt(jtf_origen.getText()) - 1).getY() + 5, listaNodos.get(Integer.parseInt(jtf_destino.getText()) - 1).getX() + 5, listaNodos.get(Integer.parseInt(jtf_destino.getText()) - 1).getY() + 5);
            lines.add(new Linea(Integer.parseInt(jtf_origen.getText()), Integer.parseInt(jtf_destino.getText())));
            listaNodos.get(Integer.parseInt(jtf_origen.getText()) - 1).nodos.add(listaNodos.get(Integer.parseInt(jtf_destino.getText()) - 1));
            listaNodos.get(Integer.parseInt(jtf_destino.getText()) - 1).nodos.add(listaNodos.get(Integer.parseInt(jtf_origen.getText()) - 1));
        }
    }//GEN-LAST:event_jb_dibujarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        for (int i = 0; i < jtf_camino.getText().length(); i++) {
            if (jtf_camino.getText().charAt(i) != ',') {
                camino.add(Character.getNumericValue(jtf_camino.getText().charAt(i)));
            }
        }
        System.out.println(validarcamino(camino, listaNodos.get(camino.get(0))));
        c.setColor(Color.RED);
        
        

    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed
        jp_pizarra.removeAll();
        jp_pizarra.repaint();
        lines.removeAll(lines);
        listaNodos.removeAll(listaNodos);
        cont=0;
        camino.removeAll(camino);
    }//GEN-LAST:event_jb_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public boolean validarcamino(ArrayList camino, Nodo nodo) {
        int bandera=camino.size();
        Nodo nuevonodo = new Nodo();
        if (!camino.isEmpty()) {
            for (int i = 0; i < nodo.nodos.size(); i++) {
                if (Integer.parseInt(camino.get(0).toString()) == nodo.nodos.get(i).getNum()) {
                    camino.remove(0);
                    nuevonodo=nodo.nodos.get(i);
                    c.drawLine(nodo.getX()+5, nodo.getY()+5, nuevonodo.getX()+5, nuevonodo.getY()+5);
                    i = nodo.nodos.size();
                }
            }
            if(camino.size()==bandera){
                return false;
            }else{
                return validarcamino(camino,nuevonodo);
            }
        }
        else {
            return true;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jb_agregarnodo;
    private javax.swing.JButton jb_dibujar;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JPanel jp_mainpanel;
    private javax.swing.JPanel jp_pizarra;
    private javax.swing.JTextField jtf_camino;
    private javax.swing.JTextField jtf_destino;
    private javax.swing.JTextField jtf_origen;
    // End of variables declaration//GEN-END:variables
 int cont = 0;
    ArrayList<Integer> camino = new ArrayList();
}
