/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotdc;

import java.util.ArrayList;
import javax.swing.JLabel;

public class Nodo extends javax.swing.JPanel {

    private int num;
    ArrayList<Nodo> nodos = new ArrayList();
    /**
     * Creates new form Nodo
     */
    public Nodo(int num) {
        initComponents();
        this.num=num;
        jl_nodo.setText(num+"");
        this.setBounds(0, 0, 10, 20);
        this.setVisible(true);
    }

    @Override
    public String toString() {
        return num+" " ;
    }

    public Nodo() {
    }

    public ArrayList<Nodo> getNodos() {
        return nodos;
    }

    public void setNodos(ArrayList<Nodo> nodos) {
        this.nodos = nodos;
    }

    public int getNum() {
        return num;
    }

    public void setNum(int num) {
        this.num = num;
    }

    public JLabel getJl_nodo() {
        return jl_nodo;
    }

    public void setJl_nodo(JLabel jl_nodo) {
        this.jl_nodo = jl_nodo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_nodo = new javax.swing.JLabel();

        jl_nodo.setBackground(new java.awt.Color(0, 51, 102));
        jl_nodo.setForeground(new java.awt.Color(0, 51, 102));
        jl_nodo.setText("      *");
        jl_nodo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jl_nodoMouseDragged(evt);
            }
        });
        jl_nodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_nodoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jl_nodoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_nodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_nodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jl_nodoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_nodoMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jl_nodoMouseDragged

    private void jl_nodoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_nodoMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jl_nodoMousePressed

    private void jl_nodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_nodoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_nodoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_nodo;
    // End of variables declaration//GEN-END:variables
int x, y;
}
